services:

  project_alpine:
    container_name: project_alpine_container
    build:
      context: ../
      dockerfile: ./docker/alpine/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../:/app
      - /app/node_modules
    env_file:
      - ./alpine/.env
    tty: true
    stdin_open: true
